#!/usr/bin/env sh

# Usage:
#   $ ./clojure [-cp "/path/to/a:/path/to/b"] [script]
#
# NB: requires `rlwrap` for REPL convenience

classpath="$CLOJURE_HOME/clojure.jar"

if [ "$1" = "-cp" ]; then
	shift
	classpath="$classpath:$1"
	shift
fi

cmd="java -cp $classpath clojure.main $@"
if [ -z "$@" ]; then # REPL
	rlwrap $cmd
else
	$cmd
fi
